version: '3'
services:
  mysql-dev:
    image: mysql:9.1.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: sleepa_dev
      MYSQL_USER: sleepa
      MYSQL_PASSWORD: sleepa
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-dev-data:/var/lib/mysql
  
  mysql-test:
    image: mysql:9.1.0
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: sleepa_test
      MYSQL_USER: sleepa
      MYSQL_PASSWORD: sleepa
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-test-data:/var/lib/mysql

  redis-dev:
    image: redis:7.4.2
    ports:
      - 6380:6379
    restart: always

  elasticsearch-dev:
    image: elasticsearch:8.16.2
    environment:
      - ELASTIC_PASSWORD=sleepa
      - KIBANA_PASSWORD=sleepa
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - 9201:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  kibana-dev:
    image: kibana:8.16.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-dev:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=sleepa
      - SERVER_SSL_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
    ports:
      - 5602:5601
    restart: always
    depends_on:
      - elasticsearch-dev
 
volumes:
  mysql-dev-data:
  mysql-test-data:
  es-data:
